### ISSUE TITLE
Could not parse content body of request

### ISSUE THREAD

**Issue by georgeOsdDev** [xitrum-framework/xitrum#659] opened 2017-12-01 11:30 UTC
Some error occur when POST requests from multiple clients concentrate.

xitrum@3.28.6
```
@POST("http_test")
class HttpTest extends Action with SkipCsrfCheck {
  def execute() {
    respondText("aaa")
  }
}
```

Client code
```
import java.io.OutputStreamWriter
import java.net.HttpURLConnection
import java.net.URL

import scala.concurrent.Future
import scala.concurrent.Await
import scala.concurrent.duration.Duration
import scala.io.Source

object TestMain {
  val URL = "http://localhost:8000/http_test"
  val THREAD_NUM = 10
  val LOOP = 10

  def main(args: Array[String]): Unit = {
    import scala.concurrent.ExecutionContext.Implicits.global
    val ret = (0 until THREAD_NUM) map { i =>
      Future {
        try {
          (0 until LOOP) foreach { j =>
            post(i, j)
          }
        } catch {
          case e: Throwable =>
            println(s"${e.getClass} ${e.getMessage}")
        }
      }
    }
    Await.result(Future.sequence(ret), Duration.Inf)
  }

  def post(i: Int, j: Int): Unit = {
    val conn = new URL(URL).openConnection().asInstanceOf[HttpURLConnection]
    conn.setRequestMethod("POST")
    conn.setDoOutput(true)
    conn.setConnectTimeout(1000)
    conn.setReadTimeout(1000)
    conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded; charset=utf-8")
    val out = new OutputStreamWriter(conn.getOutputStream())
    val data = (0 until 50).map { i => s"param_${i}=${"v"*100}_${i}" }.mkString("&")
    out.write(data)
    out.close()
    val content = try {
      val in = Source.fromInputStream(conn.getInputStream())(scala.io.Codec.UTF8)
      val ret = in.mkString
      in.close()
      ret
    } catch {
      case e: Throwable => s"${e.getClass} ${e.getMessage}"
    }
    println(s"${conn.getResponseCode()} ${conn.getResponseMessage()} ${content}")
    conn.disconnect()
  }
}
```

xitrum.log
```
[DEBUG] Could not parse content body of request: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 5629, widx: 5629, cap: 5629/5629, unwrapped: PooledUnsafeDirectByteBuf(ridx: 5629, widx: 5629, cap: 16384)), decoderResult: success)
java.lang.NullPointerException: null

[DEBUG] Could not parse content body of request: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 1024, widx: 1024, cap: 1024/1024, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1024, widx: 1024, cap: 1024)), decoderResult: success)
java.lang.NullPointerException: null
[WARN] Caught exception
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at io.netty.handler.codec.http.multipart.DefaultHttpDataFactory.cleanRequestHttpData(DefaultHttpDataFactory.java:252)
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.cleanFiles(HttpPostStandardRequestDecoder.java:678)
        at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.cleanFiles(HttpPostRequestDecoder.java:252)
        at xitrum.handler.HandlerEnv.release(HandlerEnv.scala:96)
        at xitrum.handler.inbound.Request2Env.channelInactive(Request2Env.scala:70)
        （略）
[WARN] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: promise already done: DefaultChannelPromise@7659c90d(failure: java.lang.NullPointerException)
        at io.netty.channel.AbstractChannelHandlerContext.isNotValidPromise(AbstractChannelHandlerContext.java:910)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:714)
        at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:304)
        at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:137)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
        （略）
```

Client log
```
400 Bad Request class java.io.IOException Server returned HTTP response code: 400 for URL: http://localhost:8000/http_test

200 OK aaa

class java.net.SocketTimeoutException Read timed out
```

**Comment by ngocdaothanh** [comment] 2017-12-15 05:32
There are (different?) errors when testing with `ab`:

```
ab -T 'application/x-www-form-urlencoded' -n 100 -c 5 -p post.txt http://localhost:8000/http_test
```

post.txt file:

```
a=1&b=2
```

**Comment by ngocdaothanh** [comment] 2017-12-15 06:22
It seems that the problem has been introduced from a commit later than this commit:

```
commit 712426f795f5b0ed2e8efba97de1e8a942f75615
Update Xitrum from 3.25.0 to 3.26.0
```

**Comment by alide** [comment] 2017-12-16 19:41
The problem has been introduced to xitrum-new at commit:
https://github.com/xitrum-framework/xitrum-new/commits/master

```
3a65815
Update Xitrum from 3.26.0 to 3.26.1
```

xitrum diff:
https://github.com/xitrum-framework/xitrum/compare/3.26.0...3.26.1

**Comment by ngocdaothanh** [comment] 2017-12-18 01:12
The problem has been introduced when updating Netty from 4.0.x to 4.1.x at this commit:
https://github.com/xitrum-framework/xitrum/commit/87e7e12fa54f2f3d7594a24219fb90021e72e5f8

**Comment by ngocdaothanh** [comment] 2017-12-19 23:36
I think the root cause is in Netty 4.1.x.

The upload server example in Netty also has similar problem:
https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http/upload

Start HttpUploadServer at port 8000, and use this command to reproduce the problem:

```
ab -T 'application/x-www-form-urlencoded' -n 100 -c 5 -p post.txt http://localhost:8000/form
```

It seems that the cause is at [DefaultHttpDataFactory#requestFileDeleteMap](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/multipart/DefaultHttpDataFactory.java): different requests are put under one same key.

I'll investigate more and report the problem to Netty developers.

**Comment by ngocdaothanh** [comment] 2017-12-20 03:19
I've created a PR to Netty:
https://github.com/netty/netty/pull/7527

**Comment by ngocdaothanh** [comment] 2017-12-28 12:29
The PR has been merged. Let's hope a new version of Netty will be released soon.

**Comment by ngocdaothanh** [comment] 2018-01-24 00:10
Netty 4.1.20 has been released:
* http://netty.io/news/2018/01/22/4-0-55-Final-4-1-20-Final.html
* https://github.com/netty/netty/milestone/180?closed=1

It fixed the problem.
I'll release a new Xitrum version in a few hours.

**Closed by ngocdaothanh** 2018-01-24 00:10 UTC
Labels: Bug
